DROP TABLE public."commodityProduceInventory";
DROP TABLE public."annualInfo";
DROP TABLE public."associationToProgram";
DROP TABLE public."householdToProgram";
DROP TABLE public."household";
DROP TABLE public."commodity";
DROP TABLE public."program";
DROP TABLE public."farm";
DROP TABLE public."association";