-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."commodityProduce" add column "produceInUnit" numeric
--  null default '0';
